services:
  elasticsearch:
    build: .
    image: elasticsearch:nori
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 없으면 접속 정보를 작성해야 한다